class AddBettingOddsToGames < ActiveRecord::Migration
  def change
    add_column :games, :b365h, :float
    add_column :games, :b365d, :float
    add_column :games, :b365a, :float
    add_column :games, :bsh, :float
    add_column :games, :bsd, :float
    add_column :games, :bsa, :float
    add_column :games, :bwh, :float
    add_column :games, :bwd, :float
    add_column :games, :bwa, :float
    add_column :games, :gb, :float
    add_column :games, :gbd, :float
    add_column :games, :gba, :float
    add_column :games, :iwh, :float
    add_column :games, :iwd, :float
    add_column :games, :iwa, :float
    add_column :games, :lbh, :float
    add_column :games, :lbd, :float
    add_column :games, :lba, :float
    add_column :games, :psh, :float
    add_column :games, :psd, :float
    add_column :games, :psa, :float
    add_column :games, :soh, :float
    add_column :games, :sod, :float
    add_column :games, :soa, :float
    add_column :games, :sbh, :float
    add_column :games, :sbd, :float
    add_column :games, :sba, :float
    add_column :games, :sjh, :float
    add_column :games, :sjd, :float
    add_column :games, :sja, :float
    add_column :games, :syh, :float
    add_column :games, :syd, :float
    add_column :games, :sya, :float
    add_column :games, :vch, :float
    add_column :games, :vcd, :float
    add_column :games, :vca, :float
    add_column :games, :whh, :float
    add_column :games, :whd, :float
    add_column :games, :wha, :float
    add_column :games, :bb1x2, :integer
    add_column :games, :bbmxh, :float
    add_column :games, :bbavh, :float
    add_column :games, :bbmxd, :float
    add_column :games, :bbavd, :float
    add_column :games, :bbmxa, :float
    add_column :games, :bbava, :float
    add_column :games, :bbou, :integer
    add_column :games, :bbmx_over_two_point_five, :float
    add_column :games, :bbav_over_two_point_five, :float
    add_column :games, :bbmx_under_two_point_five, :float
    add_column :games, :bbav_under_two_point_five, :float
  end
end
